import { randomUUID } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CompressedMemory, ContextGraph, DevelopmentTrack, TrackItem } from '../../core/types.js';

export class DevelopmentTrackingEngine {
  private outputDir: string;
  private sprintNumber = 1;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
    fs.mkdirSync(outputDir, { recursive: true });
    this.loadSprintNumber();
  }

  generate(memory: CompressedMemory, graph: ContextGraph): DevelopmentTrack {
    const track = this.buildTrack(memory, graph);
    this.writeTrackingDocs(track, graph);
    this.writeSprintDoc(track);
    this.saveSprintNumber();
    return track;
  }

  private buildTrack(memory: CompressedMemory, graph: ContextGraph): DevelopmentTrack {
    const milestones = memory.facts.filter((f) => f.type === 'milestone');
    const decisions = memory.facts.filter((f) => f.type === 'decision');
    const lessons = memory.facts.filter((f) => f.type === 'lesson');
    const risks = memory.facts.filter((f) => f.type === 'risk');
    const metrics = memory.facts.filter((f) => f.type === 'metric');
    const now = new Date().toISOString();

    const toTrackItem = (f: typeof memory.facts[0], category: string): TrackItem => ({
      id: f.id,
      content: f.content,
      addedAt: f.timestamp,
      confidence: f.confidence,
      source: f.source,
      category,
    });

    const completed = milestones
      .filter((m) => m.confidence > 0.8)
      .map((m) => toTrackItem(m, 'completed'));

    const inProgress = milestones
      .filter((m) => m.confidence <= 0.8 && new Date(m.timestamp).getTime() > Date.now() - 7 * 24 * 60 * 60 * 1000)
      .map((m) => toTrackItem(m, 'in-progress'));

    const blockers: TrackItem[] = [
      ...lessons.filter((l) => l.tags.includes('breaking')).map((l) => toTrackItem(l, 'blocker')),
      ...risks.map((r) => toTrackItem(r, 'blocker')),
    ];

    const decisionItems = decisions.map((d) => toTrackItem(d, 'decision'));

    const nowD = Date.now();
    const sevenDaysAgo = nowD - 7 * 24 * 60 * 60 * 1000;
    const staleComponents = graph.nodes
      .filter((n) => n.type === 'component' && n.metadata.lastChanged && new Date(n.metadata.lastChanged as string).getTime() < sevenDaysAgo)
      .map((n): TrackItem => ({ id: randomUUID(), content: `Component ${n.label} may need updates`, addedAt: n.metadata.lastChanged as string, confidence: 0.5, source: 'graph', category: 'planned' }));

    const featureNodes = graph.nodes.filter((n) => n.type === 'feature');
    const plannedFeatures = featureNodes
      .filter((n) => { const ts = n.metadata.timestamp as string; return ts && new Date(ts).getTime() < sevenDaysAgo; })
      .map((n): TrackItem => ({ id: randomUUID(), content: n.label, addedAt: (n.metadata.timestamp as string) || now, confidence: 0.6, source: 'graph', category: 'planned' }));

    return {
      completed,
      inProgress,
      planned: [...plannedFeatures, ...staleComponents],
      blockers,
      decisions: decisionItems,
      lastUpdated: now,
      sprintNumber: this.sprintNumber,
    };
  }

  private writeTrackingDocs(track: DevelopmentTrack, graph: ContextGraph): void {
    const tracking = [
      '# Development Tracking',
      '',
      `> Auto-generated by Vibe Context Engineer Agent`,
      `> Last updated: ${track.lastUpdated}`,
      `> Sprint: #${track.sprintNumber}`,
      '',
      '## Completed',
      ...track.completed.map((i) => `- [x] ${i.content}`),
      '',
      '## In Progress',
      ...track.inProgress.map((i) => `- [ ] ${i.content}`),
      '',
      '## Planned',
      ...track.planned.map((i) => `- [ ] ${i.content}`),
      '',
      '## Blockers',
      ...(track.blockers.length > 0 ? track.blockers.map((i) => `- ⚠️ ${i.content}`) : ['None']),
      '',
      '## Architecture Decisions',
      ...track.decisions.map((i) => `- 📐 ${i.content}`),
      '',
    ].join('\n');

    const adr = [
      '# Architecture Decision Records',
      '',
      `> Auto-generated: ${track.lastUpdated}`,
      '',
      ...track.decisions.map((item, i) => [
        `## ADR-${String(i + 1).padStart(3, '0')}`,
        '',
        `**Status**: Accepted`,
        `**Date**: ${track.lastUpdated}`,
        '',
        '### Context',
        item.content,
        '',
        '### Decision',
        'Based on analysis of repository changes.',
        '',
        '### Consequences',
        'Documented for future agent context.',
        '',
      ].join('\n')),
    ].join('\n');

    const graphDoc = [
      '# Context Graph Summary',
      '',
      `> Auto-generated: ${graph.lastUpdated}`,
      '',
      `## Nodes (${graph.nodes.length})`,
      ...graph.nodes.map((n) => `- **${n.type}**: \`${n.id}\` → ${n.label} (v${n.version})`),
      '',
      `## Relations (${graph.relations.length})`,
      ...graph.relations.map((r) => `- \`${r.source}\` → **${r.type}** → \`${r.target}\``),
      '',
    ].join('\n');

    fs.writeFileSync(path.join(this.outputDir, 'DEVELOPMENT-TRACKING.md'), tracking);
    fs.writeFileSync(path.join(this.outputDir, 'ARCHITECTURE-DECISIONS.md'), adr);
    fs.writeFileSync(path.join(this.outputDir, 'CONTEXT-GRAPH.md'), graphDoc);
  }

  private writeSprintDoc(track: DevelopmentTrack): void {
    const sprint = [
      '# Current Sprint',
      '',
      `> Sprint #${track.sprintNumber} — Auto-generated: ${track.lastUpdated}`,
      '',
      '## Active Work',
      ...track.inProgress.map((i) => `- ${i.content}`),
      '',
      '## Recent Completions',
      ...track.completed.slice(0, 10).map((i) => `- ✓ ${i.content}`),
      '',
      '## Next Up',
      ...track.planned.slice(0, 5).map((i) => `- ${i.content}`),
      '',
      '## Blocked',
      ...(track.blockers.length > 0 ? track.blockers.map((i) => `- 🚫 ${i.content}`) : ['Nothing blocked']),
      '',
    ].join('\n');

    const nextSteps = [
      '# Next Steps',
      '',
      `> Auto-generated: ${track.lastUpdated}`,
      '',
      ...track.planned.map((i) => `- [ ] ${i.content}`),
      ...track.blockers.map((i) => `- ⚠️ Blocker: ${i.content}`),
      ...(track.planned.length === 0 && track.blockers.length === 0 ? ['- No pending items'] : []),
      '',
    ].join('\n');

    fs.writeFileSync(path.join(this.outputDir, 'CURRENT-SPRINT.md'), sprint);
    fs.writeFileSync(path.join(this.outputDir, 'NEXT-STEPS.md'), nextSteps);
  }

  private loadSprintNumber(): void {
    try {
      const p = path.join(this.outputDir, 'sprint-state.json');
      if (fs.existsSync(p)) {
        const state = JSON.parse(fs.readFileSync(p, 'utf-8'));
        this.sprintNumber = state.sprintNumber || 1;
      }
    } catch {}
  }

  private saveSprintNumber(): void {
    fs.writeFileSync(
      path.join(this.outputDir, 'sprint-state.json'),
      JSON.stringify({ sprintNumber: this.sprintNumber, lastUpdated: new Date().toISOString() })
    );
  }

  advanceSprint(): void {
    this.sprintNumber++;
    this.saveSprintNumber();
  }
}
